### Your name:

<pre> Jivitesh Shah</pre>

### Title:

<pre> Here we study the theroy and implementation for K Nearest Neighbours </pre>


In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Markdown referece can be found here:
    http://nestacms.com/docs/creating-content/markdown-cheat-sheet

Q1. Why would it be a problem if our training set and test set are the same.

<pre> If the training and test set are the same, our model would perform well on the training as well as test set but might not permorm well on new data set. In order for us to have our model perform well on new data, it is advisable to use training set for training the model, a different validation set for validating the model and finally a new testing set to test the model. </pre>

Q2. Explain step by step the process to select k in the k-nearest neighbor algorithm (pseudocode)

<pre> 
In order for us to select the best possible k in k-nearest neighbor algorithm, we perfom cross validation on training set and run KNN on that. We can use K Fold cross validation to select optimal k, as shown below:

#From training set, split data into K folds, creating a kFolds array
kFolds[] = training_set
#create kList, a list of random k's for KNN
kList[] = random(1,10)

#Run KNN on the split data. In each iteration, 1st fold is treated as validation set and remaining k-1 as training set
for each k in kList
    run KNN on k-1 kFolds[]
    fit KNN on the 1st kFold[] as Validation set
    calculate error and store in error array
    move kFold pointer by 1 so now we use a different sets as validation and training 
From the list of error, select the min, the k corresponding to that mean is our optimal K in KNN
</pre>

Q3. For the k-nearest regression. What happends when k = n. Where n is equal tot he training size.

<pre> If we set k = n, we may end up looking at samples that are not neighbours. </pre>

Q4. Define a function that takes a 1-d numpy array, a parameter k, and a number p.
The function returns an estimate equal to the mean of the closest k points to the number p

In [2]:
# From the question, it is understood to return the mean of calculated k points to the number p
# For this, I will calculate the absolute value for each element in the array and pick smalled k points and return the mean
from heapq import nsmallest
def k_neighbor(s, k, p):
    return np.mean(nsmallest (k, s, key=lambda x: abs(x-p)))
    
    

In [3]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor(s=data, k=3, p=5))
print(k_neighbor(s=data, k=2, p=15))
print(k_neighbor(s=data, k=3, p=25))
print(k_neighbor(s=data, k=1, p=55))
print(k_neighbor(s=data, k=3, p=55))
print(k_neighbor(s=data, k=10, p=55))

4.0
14.0
26.0
40.0
31.333333333333332
19.6


In [4]:
#Based on nsmallest documentation, it makes a single pass over the data, keeping no more than k best values in memory each time

Q5. Similar to Q4 but for the n dimentional case. 

In [5]:
from sklearn.neighbors import KNeighborsRegressor

def l1_norm(a,b):
    """Returns the l1 norm (a,b)"""
    return np.sum(np.abs(a - b))
    
def l2_norm(a,b):
    """Returns the l2 norm (a,b)""" 
    return np.sqrt(np.sum(np.square(a - b)))
 
def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
    mode -- estimator possible values = 'mean', 'median', 'max'
    
    Implement the l1 and l2 norms
    for mean, median and max, use np.mean, np.median and np.max
    """
    distances = []
    for i in range(len(input_data)):
        if (metric == 'l1'):
            distance = l1_norm(input_data[i,:],p)
        else:
            distance = l2_norm(input_data[i,:],p)
        distances.append([distance, i])
        
    distances = sorted(distances)
    
    output = []
    for i in range(k):
        index = distances[i][1]
        output.append(input_data[index])

    if (mode == 'mean'):
        return np.mean(output, axis = 1)
    elif (mode == 'median'):
        return np.median(output, axis = 1)
    else:
        return np.amax(output, axis = 1)
    
    #return answer
    
   

In [6]:
data_4d = np.array([[4, 1, 2, 1], [1, 4, 2, 0], [3, 3, 1, 1], 
        [4, 0, 0, 0], [1, 2, 0, 0], [3, 4, 2, 3], 
        [2, 4, 4, 2], [2, 1, 4, 1], [3, 3, 2, 4], 
        [4, 3, 0, 4], [2, 2, 4, 0],[4, 3, 0, 2], 
        [4, 3, 0, 2], [0, 3, 4, 2]])

In [7]:
#Evaluate   
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l1', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l1', mode='median'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l2', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l2', mode='median'))

[2. 3. 2.]
[2.25 2.25]
[4 4 4]
[3.]
[3. 3. 3.]
[2.   2.25 3.  ]
[2.   2.25]
[4 4 4]
[3.]
[3. 3. 3.]


In [8]:
# In the above implementation, we calculate the distance of each element in the 4D Vector with p, either L1 or L2, sort the distances in ascending order and then return the mean, median or max of each target values

Q6. Read the documentation on KNeighborsRegressor

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    
Explore the source code:
    https://github.com/scikit-learn/scikit-learn/blob/ef5cb84a/sklearn/neighbors/regression.py
        
How different it is from your implementation? How well can you follow the code? Did you learn something new?

<pre>The current implementation is not very different from the implementation of KNeighborsRegressor. Both implementations consider mean distance, uniform weights and are used for continuous data labels. 

It was difficult at first to follow the code on the github page without having prior python experience, but after spending some time with the documentations, I understood the implementation of KNN Regressor.

Lastly, I did learn variations in kNN, cross validation to find optimal k and regression and classification.
I also learnt different kNN algorithms such as KDTree and BallTree</pre>